kind: Deployment
apiVersion: apps/v1
metadata:
  name: qsk-deploy
spec:
  replicas: 10          #   <<== Change this to 10
  selector:
    matchLabels:
      project: qsk-book
  template:
    metadata:
      labels:
        project: qsk-book
    spec:
      containers:
        - name: qsk-pod
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          image: nigelpoulton/qsk-book:1.0
