apiVersion: v1
kind: Service
metadata:
  name: backend  #
spec:
  type: NodePort  # ClusterIP, NodePort, LoadBalancer, ExternalName
  ports:
    - port: 8080
      protocol: TCP  #TCP, UDP, SCTP
      targetPort: 8080
      nodePort: 31111 # localhost:31111
  selector:
    project: backend  # label
  sessionAffinity: ClientIP # client ip address boyicha eski serverga junatadi

